"""
PlacementPulse - README Generator
Generates a clean, elegant README with today's snapshot.
"""

from __future__ import annotations

import sys
from collections import Counter
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import List

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from scripts.core.models import Opportunity
from scripts.core.logger import get_logger
from config.settings import ROOT_DIR

log = get_logger("generator.readme")

README_PATH = ROOT_DIR / "README.md"

CAT_EMOJI = {
    "internship": "🎓",
    "fresher-job": "💼",
    "off-campus-drive": "🚀",
    "hiring-challenge": "⚡",
    "hackathon": "🏆",
    "fellowship": "🌟",
    "open-source-program": "🔓",
    "student-ambassador": "📢",
    "scholarship": "📚",
}


def generate_readme(
    all_opps: List[Opportunity],
    today_opps: List[Opportunity],
    stats: dict,
) -> Path:
    today = date.today()
    active = [o for o in all_opps if not o.is_expired()]
    company_counts = Counter(o.company for o in all_opps)
    cat_counts = Counter(o.category for o in all_opps)
    today_cats = Counter(o.category for o in today_opps)

    # ── Today's snapshot (top 3 categories only) ──────────────────────────────
    today_lines = []
    for cat, count in sorted(today_cats.items(), key=lambda x: -x[1])[:5]:
        today_lines.append(
            f"&nbsp;&nbsp;{CAT_EMOJI.get(cat, '•')} **{count}** {cat.replace('-', ' ').title()}"
        )
    today_snapshot = " &nbsp;·&nbsp; ".join(today_lines) or "No new opportunities scraped today"

    # ── Recent 10 opportunities (clean table) ─────────────────────────────────
    recent = sorted(all_opps, key=lambda o: o.date_found or "", reverse=True)[:10]
    rows = []
    for o in recent:
        mode = {"remote": "🌐 Remote", "onsite": "🏢 Onsite", "hybrid": "🔀 Hybrid"}.get(o.work_mode, "—")
        cat_label = CAT_EMOJI.get(o.category, "•") + " " + o.category.replace("-", " ").title()
        title = o.title[:50] + ("…" if len(o.title) > 50 else "")
        company = o.company[:22]
        rows.append(f"| [{title}]({o.apply_link}) | {company} | {cat_label} | {mode} |")
    recent_table = "\n".join(rows)

    # ── Category pills ─────────────────────────────────────────────────────────
    cat_pills = " · ".join(
        f"[{CAT_EMOJI.get(c, '')} {c.replace('-', ' ').title()} **{n}**](categories/{c}/)"
        for c, n in sorted(cat_counts.items(), key=lambda x: -x[1])
    )

    # ── Archive (last 5 days) ──────────────────────────────────────────────────
    archive = []
    for i in range(5):
        d = today - timedelta(days=i)
        path = f"daily/{d.year}/{d.strftime('%B')}/{d.isoformat()}.md"
        label = f"**Today** — {d.strftime('%b %d, %Y')}" if i == 0 else d.strftime("%b %d, %Y")
        archive.append(f"- [{label}]({path})")
    archive_md = "\n".join(archive)

    readme_content = f"""\
<!-- AUTO-GENERATED BY PLACEMENTPULSE BOT — DO NOT EDIT MANUALLY -->

<div align="center">

<br>

<img src="https://readme-typing-svg.demolab.com?font=Fira+Code&size=28&pause=1000&color=6C63FF&center=true&vCenter=true&width=600&lines=PlacementPulse+%F0%9F%87%AE%F0%9F%87%B3;India's+Job+%26+Internship+Hub;Updated+Twice+Daily+%E2%9C%85;100%25+Free+%26+Open+Source" alt="PlacementPulse" />

<br><br>

[![Location](https://img.shields.io/badge/📍%20Location-India-FF9933?style=for-the-badge)](#)
[![Total](https://img.shields.io/badge/Opportunities-{len(all_opps)}-6C63FF?style=for-the-badge)](#)
[![Active](https://img.shields.io/badge/Active-{len(active)}-00C853?style=for-the-badge)](#)
[![Updated](https://img.shields.io/badge/Updated-{today.strftime("%b %d %Y").replace(" ", "%20")}-0D96F2?style=for-the-badge)](#)

<br>

> **India's open-source hub for software internships, fresher jobs,**
> **hackathons & placement opportunities — auto-updated every day.**

<br>

[Browse Opportunities](#-latest-opportunities) &nbsp;·&nbsp;
[Categories](categories/) &nbsp;·&nbsp;
[Companies](companies/) &nbsp;·&nbsp;
[Daily Archive](daily/) &nbsp;·&nbsp;
[Contribute](CONTRIBUTING.md)

</div>

<br>

---

## 📅 Today &nbsp;—&nbsp; {today.strftime("%B %d, %Y")}

{today_snapshot}

<sub>🔄 Auto-scraped at 11:00 AM & 7:00 PM IST via [GitHub Actions](.github/workflows/)</sub>

---

## 🔥 Latest Opportunities

| Role | Company | Category | Location |
|------|---------|----------|----------|
{recent_table}

<div align="right">

[→ See all {len(all_opps)} opportunities](categories/)

</div>

---

## 📂 Browse by Category

{cat_pills}

---

## 🏢 Companies

[Google](companies/google/) &nbsp;·&nbsp;
[Microsoft](companies/microsoft/) &nbsp;·&nbsp;
[Amazon](companies/amazon/) &nbsp;·&nbsp;
[Apple](companies/apple/) &nbsp;·&nbsp;
[Adobe](companies/adobe/) &nbsp;·&nbsp;
[NVIDIA](companies/nvidia/) &nbsp;·&nbsp;
[Razorpay](companies/razorpay/) &nbsp;·&nbsp;
[Zoho](companies/zoho/) &nbsp;·&nbsp;
[Flipkart](companies/flipkart/) &nbsp;·&nbsp;
[Swiggy](companies/swiggy/) &nbsp;·&nbsp;
[Atlassian](companies/atlassian/)

---

## 📆 Daily Archive

{archive_md}

[→ Full archive](daily/)

---

## 📚 Resources

[Resume Templates](resources/resume/) &nbsp;·&nbsp;
[Learning Roadmaps](resources/roadmaps/) &nbsp;·&nbsp;
[Contributing Guide](CONTRIBUTING.md) &nbsp;·&nbsp;
[Setup Guide](SETUP.md)

---

<div align="center">

<sub>Built with ❤️ for Indian students &nbsp;·&nbsp; No API keys &nbsp;·&nbsp; 100% free &nbsp;·&nbsp; Auto-updated daily</sub>

<br>

<sub><i>Last generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC &nbsp;·&nbsp; {len(company_counts)} companies tracked</i></sub>

</div>
"""

    README_PATH.write_text(readme_content, encoding="utf-8")
    log.info("Generated README.md (%d bytes)", len(readme_content))
    return README_PATH
